# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration-reference

api_version = "2025-10"

[[extensions]]

uid = "8857175b-72bd-0ddd-fc49-2dbafcd4dd8d43f51242"

type = "ui_extension"
name = "checkout-discount-applier"
handle = "checkout-discount-applier"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/index.jsx"

