# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration-reference

api_version = "2026-01"

[[extensions]]
uid = "1843a996-fbce-cb52-634e-c700a398c442b43f6bc6"
type = "theme_app_extension"
name = "storefront-script"
handle = "storefront-script"

