# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f232a78339525e79f08b9bcec3b61b8f"
name = "Gachi Rewards"
application_url = "https://restrictions-catalogue-lined-mile.trycloudflare.com/"  # Local dev tunnel URL
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"
  format = "json"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
  format = "json"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"
  format = "json"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"
  format = "json"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,write_app_proxy,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [ "https://restrictions-catalogue-lined-mile.trycloudflare.com/auth" ]  # Local dev tunnel URL + /auth

[app_proxy]
url = "https://restrictions-catalogue-lined-mile.trycloudflare.com/apps/gachi-rewards"  # Local dev tunnel URL + /apps/gachi-rewards
subpath = "gachi-rewards"
prefix = "apps"
