# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration-reference

api_version = "2025-10"

[[extensions]]

uid = "3da27348-cbb8-f071-47dc-b9921f51fc840f4a3c67"

type = "ui_extension"
name = "thank-you-referral"
handle = "thank-you-referral"

[[extensions.targeting]]
target = "purchase.checkout.thank-you.block.render"
module = "./src/index.jsx"

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
optional = false
default = "Share and earn rewards!"

[[extensions.settings.fields]]
key = "api_url"
type = "single_line_text_field"
name = "API URL"
optional = false
default = "/apps/gachi-rewards/api/generate"

